config/routes.rb
Rails.application.routes.draw do
  resources :organizations, except: :index, path: 'verbaende'
  get '/verbaende', to: redirect('/'), as: :organizations_index

  # resources :documents, path: 'd'
  resources :ministries, path: 'ministerien'

  resources :laws, path: 'gesetze' do
    resources :drafts, except: :index
    resources :comments, path: 's', except: :index
  end

  get 'status' => 'site#status'

  get '/:letter', to: 'site#index', constraints: { letter: /[[:alpha:]]{1,2}/ }

  root 'site#index'
end

app/models/ministry.rb
class Ministry < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  validates_presence_of :name, :slug

  has_and_belongs_to_many :laws

  def full_name
    name + (short_name.blank? ? '' : " (#{short_name})")
  end
end

app/controllers/ministries_controller.rb
class MinistriesController < ApplicationController
  before_action :set_ministry, only: [:show, :edit, :update, :destroy]
  before_action :authenticate!, except: [:index, :show]

  # GET /ministries
  # GET /ministries.json
  def index
    @ministries = Ministry.all
  end

  # GET /ministries/1
  # GET /ministries/1.json
  def show
  end

  # GET /ministries/new
  def new
    @ministry = Ministry.new
  end

  # GET /ministries/1/edit
  def edit
  end

  # POST /ministries
  # POST /ministries.json
  def create
    @ministry = Ministry.new(ministry_params)

    respond_to do |format|
      if @ministry.save
        format.html { redirect_to @ministry, notice: 'Ministry was successfully created.' }
        format.json { render :show, status: :created, location: @ministry }
      else
        format.html { render :new }
        format.json { render json: @ministry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ministries/1
  # PATCH/PUT /ministries/1.json
  def update
    respond_to do |format|
      if @ministry.update(ministry_params)
        format.html { redirect_to @ministry, notice: 'Ministry was successfully updated.' }
        format.json { render :show, status: :ok, location: @ministry }
      else
        format.html { render :edit }
        format.json { render json: @ministry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ministries/1
  # DELETE /ministries/1.json
  def destroy
    @ministry.destroy
    respond_to do |format|
      format.html { redirect_to ministries_url, notice: 'Ministry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ministry
      @ministry = Ministry.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ministry_params
      params.require(:ministry).permit(:name, :short_name)
    end
end

app/helpers/ministries_helper.rb
module MinistriesHelper
end

app/views/ministries/_form.html.erb
<%= form_with(model: ministry, local: true) do |form| %>
  <% if ministry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ministry.errors.count, "error") %> prohibited this ministry from being saved:</h2>

      <ul>
      <% ministry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :ministry_name %>
  </div>

  <div class="field">
    <%= form.label :short_name %>
    <%= form.text_field :short_name, id: :ministry_short_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ministries/edit.html.erb
<div class="container">
<h1>Editing Ministry</h1>

<%= render 'form', ministry: @ministry %>

<p class="admin-controls">
<%= link_to 'Show', @ministry %> |
<%= link_to 'Back', ministries_path %>
</p>
</div>

app/views/ministries/index.html.erb
<% title 'Ministerien' %>

<header class="page-header">
  <div class="container">
    <h2><mark><%= @ministries.count %>&nbsp;Mi&shy;nis&shy;terien</mark></h2>
  </div>
</header>

<div class="container">
  <ul>
    <% @ministries.each do |ministry| %>
    <h3><li><%= link_to ministry.full_name, ministry %></li></h3>
    <% end %>
  </ul>
</div>

<% if authenticated? %>
<div class="container">
  <p id="notice"><%= notice %></p>
  <p class="admin-controls"><%= link_to 'New Ministry', new_ministry_path %></p>
</div>
<% end %>

app/views/ministries/new.html.erb
<div class="container">
<h1>New Ministry</h1>

<%= render 'form', ministry: @ministry %>

<p class="admin-controls">
<%= link_to 'Back', ministries_path %>
</p>
</div>

app/views/ministries/show.html.erb
<% title @ministry.name %>

<header class="page-header">
  <div class="container">
    <h2><%= @ministry.name %> <% unless @ministry.short_name.blank? %>(<%= @ministry.short_name %>)<% end %></h2>

    <p class="law-meta"Das Ministerium hat <%= @ministry.laws.count %> Gesetze entworfen.</p>
  </div>
</header>

<div class="container">
  <ul class="law-list">
    <%= render partial: 'laws/law', collection: @ministry.laws %>
  </ul>
</div>

<% if authenticated? %>
<div class="container">
  <p id="notice"><%= notice %></p>
  <p class="admin-controls"><%= link_to 'Edit', edit_ministry_path(@ministry) %></p>
</div>
<% end %>