config/routes.rb
Rails.application.routes.draw do
  resources :organizations, except: :index, path: 'verbaende'
  get '/verbaende', to: redirect('/'), as: :organizations_index

  # resources :documents, path: 'd'
  resources :ministries, path: 'ministerien'

  resources :laws, path: 'gesetze' do
    resources :drafts, except: :index
    resources :comments, path: 's', except: :index
  end

  get 'status' => 'site#status'

  get '/:letter', to: 'site#index', constraints: { letter: /[[:alpha:]]{1,2}/ }

  root 'site#index'
end

app/models/law.rb
class Law < ApplicationRecord
  extend FriendlyId
  friendly_id :id_and_title, use: :slugged
  validates_presence_of :title, :slug
  validates :title, uniqueness: true

  has_and_belongs_to_many :ministries
  has_many :drafts, dependent: :destroy
  has_many :comments, dependent: :destroy

  def should_generate_new_friendly_id?
    title_changed? || super
  end

  def id_and_title
    [
      [:id, :title]
    ]
  end

  def normalize_friendly_id(value)
    value.to_s.gsub('&', 'und').parameterize.truncate(120, separator: '-', omission: '')
  end
end

app/controllers/laws_controller.rb
class LawsController < ApplicationController
  before_action :set_law, only: [:show, :edit, :update, :destroy]
  before_action :authenticate!, except: [:index, :show]

  # GET /laws
  # GET /laws.json
  def index
    @laws = Law.includes(:drafts).where.not(drafts: { id: nil })
  end

  # GET /laws/1
  # GET /laws/1.json
  def show
  end

  # GET /laws/new
  def new
    @law = Law.new
  end

  # GET /laws/1/edit
  def edit
  end

  # POST /laws
  # POST /laws.json
  def create
    @law = Law.new(law_params)

    respond_to do |format|
      if @law.save
        format.html { redirect_to @law, notice: 'Law was successfully created.' }
        format.json { render :show, status: :created, location: @law }
      else
        format.html { render :new }
        format.json { render json: @law.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /laws/1
  # PATCH/PUT /laws/1.json
  def update
    respond_to do |format|
      if @law.update(law_params)
        format.html { redirect_to @law, notice: 'Law was successfully updated.' }
        format.json { render :show, status: :ok, location: @law }
      else
        format.html { render :edit }
        format.json { render json: @law.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /laws/1
  # DELETE /laws/1.json
  def destroy
    @law.destroy
    respond_to do |format|
      format.html { redirect_to laws_url, notice: 'Law was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_law
      @law = Law.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def law_params
      params.require(:law).permit(:title, ministry_ids: [])
    end
end

app/helpers/laws_helper.rb
module LawsHelper
end

app/views/laws/_form.html.erb
<%= form_with(model: law, local: true) do |form| %>
  <% if law.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(law.errors.count, "error") %> prohibited this law from being saved:</h2>

      <ul>
      <% law.errors.full_messages.each do |message| %>
        <li class="law-list"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title, id: :law_title %>
  </div>

  <div class="field">
    <%= form.label :ministry_ids %>
    <%= form.collection_select :ministry_ids, Ministry.all, :id, :name, {}, { multiple: true, id: :law_ministry_ids } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/laws/_law.html.erb
<%
organization = false if organization.nil?
%>
<li class="law-block">
  <p class="law-ministries">
    <% law.ministries.each do |ministry| %>
    <%= link_to ministry.full_name, ministry %><%= "," unless ministry == law.ministries.last %>
    <% end %>
  </p>
  <h3><%= link_to law.title, law %></h3>
  <nav>
    <% if law.drafts.empty? %>
      <%= link_to 'Referentenentwurf anfragen', "https://fragdenstaat.de/kampagne/gesetze/?q=#{law.title}" %>
    <% else %>
      <%= link_to 'zum Referentenentwurf', law_path(law, anchor: 'draft') %>
    <% end %>
    &bull;
    <% if !organization %>
      <% if law.comments.empty? %>
        <%= link_to 'Stellungnahmen anfragen', "https://fragdenstaat.de/kampagne/gesetze/?q=#{law.title}" %>
      <% else %>
        <%= link_to t(:to_comments, count: law.comments.count), law_path(law, anchor: 'comments') %>
      <% end %>
    <% else %>
      <%# FIXME: link to comments of this org %>
      <%= link_to t(:to_comments, count: law.comments.count), law_path(law, anchor: 'comments') %>
    <% end %>
  </nav>
</li>

app/views/laws/edit.html.erb
<div class="container">
  <h1>Editing Law</h1>

  <%= render 'form', law: @law %>

  <p class="admin-controls">
    <%= link_to 'Show', @law %> |
    <%= link_to 'Back', laws_path %>
  </p>
</div>

app/views/laws/index.html.erb
<% title 'Gesetze und ihre Stellungnahmen' %>

<header class="page-header">
  <div class="container">
    <h2><mark><%= @laws.count %>&nbsp;Ge&shy;setze</mark> und ihre Stellung&shy;nahmen</h2>
  </div>
</header>

<div class="container">
  <ul class="law-list">
    <%= render partial: 'laws/law', collection: @laws %>
  </ul>
</div>

<% if authenticated? %>
<div class="container">
  <p id="notice"><%= notice %></p>
  <p class="admin-controls"><%= link_to 'New Law', new_law_path %></p>
</div>
<% end %>

app/views/laws/new.html.erb
<div class="container">
  <h1>New Law</h1>

  <%= render 'form', law: @law %>

  <p class="admin-controls">
    <%= link_to 'Back', laws_path %>
  </p>
</div>

app/views/laws/show.html.erb
<%
title @law.title

ministries = @law.ministries.map { |m| m.name }
desc = "Referentenentwurf und Stellungnahmen zu #{@law.title} von #{ministries.join(', ')}"
description desc
opengraph do |graph|
  graph.title @law.title
  graph.description desc
end
twitter_card('summary') do |card|
  card.title @law.title
  card.description desc
end

%>
<header class="page-header law-header">
  <div class="container">
    <h2><%= @law.title %></h2>
    <p class="law-meta">von <% @law.ministries.each do |ministry| %>
      <%= link_to ministry.full_name, ministry %><%= "," unless ministry == @law.ministries.last %>
      <% end %>
    </p>

    <nav>
      <ul class="nav nav-tabs" role="tablist" data-tabs>
        <li role="presentation" class="active">
          <a href="#drafts" aria-controls="drafts" role="tab" data-tab data-turbolinks="false"><span>Referentenentwurf</span></a>
        </li>
        <li role="presentation">
          <a href="#comments" aria-controls="comments" role="tab" data-tab data-turbolinks="false"><span><%= t :comments, count: @law.comments.count %></span></a>
        </li>
      </ul>
    </nav>
  </div>
</header>

<div class="container">
  <div class="tab-content law-tab-content" data-tabs-content>
    <div role="tabpanel" class="tab-pane active tab-draft" data-tabs-pane id="drafts">
      <% if @law.drafts.empty? %>
      <p>
        Der Referentenentwurf für dieses Gesetz ist noch nicht öffentlich.
        <%= link_to 'Jetzt anfragen.', "https://fragdenstaat.de/kampagne/gesetze/?q=#{@law.title}" %>
      </p>
      <% end %>
      <% i = 0 %>
      <% @law.drafts.each do |draft| %>
      <% i += 1 %>
        <p><strong>Referentenentwurf #<%= i %></strong>
        <% if draft.published_at %> - Veröffentlicht am <%= l draft.published_at, format: :date %><% end %></p>
        <% if draft.document.nil? %>
        <p>
          Der Referentenentwurf für dieses Gesetz ist noch nicht öffentlich.
          <%= link_to 'Jetzt anfragen.', "https://fragdenstaat.de/kampagne/gesetze/?q=#{@law.title}" %>
        </p>
        <% else %>
        <embed src="<%= draft.document.file.url %>" width="100%" height="500" type='application/pdf' />
        <p><strong>Quelle:</strong> <%= link_to draft.document.source_url, draft.document.source_url, class: 'source-link' %></p>
        <% end %>


        <% if authenticated? %>
        <p class="admin-controls">
          <%= link_to 'Edit Draft', edit_law_draft_path(@law, draft) %> |
          <%= link_to 'Destroy', [@law, draft], method: :delete, data: { confirm: 'Are you sure?' } %>
        </p>
        <% end %>
      <% end %>
    </div>
    <div role="tabpanel" class="tab-pane tab-comments" data-tabs-pane id="comments">
      <% if @law.comments.size > 0 %>
      <nav class="filter-bar">
        <a href="#comments" class="filter-link active" data-filter="all">Alle anzeigen</a> &bull;
        <a href="#comments" class="filter-link" data-filter="published">Nur veröffentlicht</a> &bull;
        <a href="#comments" class="filter-link" data-filter="unpublished">Nur unveröffentlicht</a>
      </nav>
      <ul class="comments-list">
      <%= render partial: 'comments/comment', collection: @law.comments %>
      </ul>
      <% else %>
      <p>Es sind noch keine Stellungnahmen zu diesem Gesetz bekannt.</p>
      <% end %>
    </div>
  </div>
</div>

<% if authenticated? %>
<div class="container">
  <p id="notice"><%= notice %></p>
  <p class="admin-controls">
    <%= link_to 'Edit', edit_law_path(@law) %> |
    Drafts: <%= link_to 'New Draft', new_law_draft_path(@law) %> |
    Comments: <%= link_to 'New Comment', new_law_comment_path(@law) %>
  </p>
</div>
<% end %>