config/routes.rb
Rails.application.routes.draw do
  resources :organizations, except: :index, path: 'verbaende'
  get '/verbaende', to: redirect('/'), as: :organizations_index

  # resources :documents, path: 'd'
  resources :ministries, path: 'ministerien'

  resources :laws, path: 'gesetze' do
    resources :drafts, except: :index
    resources :comments, path: 's', except: :index
  end

  get 'status' => 'site#status'

  get '/:letter', to: 'site#index', constraints: { letter: /[[:alpha:]]{1,2}/ }

  root 'site#index'
end

app/models/organization.rb
class Organization < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  validates_presence_of :name, :slug

  has_and_belongs_to_many :comments

  def laws
    comments.map(&:law).uniq
  end


  def self.normalize(name)
    config = {
      host: Rails.configuration.x.nomenklatura_host,
      api_key: Rails.application.secrets.nomenklatura_apikey
    }
    return name if config[:host].blank? || config[:api_key].blank?
    ::Nomenklatura::Dataset.new('draft-law-comment-sources', config).lookup(name)
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]
  before_action :authenticate!, except: [:index, :show]

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_with(model: organization, local: true) do |form| %>
  <% if organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :organization_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<div class="container">
<h1>Editing Organization</h1>

<%= render 'form', organization: @organization %>

<p class="admin-controls">
<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>
</p>
</div>

app/views/organizations/new.html.erb
<div class="container">
<h1>New Organization</h1>

<%= render 'form', organization: @organization %>

<p class="admin-controls">
<%= link_to 'Back', organizations_path %>
</p>
</div>

app/views/organizations/show.html.erb
<% title @organization.name %>

<header class="page-header">
  <div class="container">
    <h2><%= @organization.name %></h2>

    <p>Der Verband wurde für <%= @organization.comments.map(&:law).uniq.count %> Gesetze angefragt.</p>
  </div>
</header>

<div class="container">
  <ul class="law-list">
    <%= render partial: 'laws/law', collection: @organization.laws, locals: { organization: @organization } %>
  </ul>
</div>

<% if authenticated? %>
<div class="container">
  <p id="notice"><%= notice %></p>
  <p class="admin-controls"><%= link_to 'Edit', edit_organization_path(@organization) %></p>
</div>
<% end %>