config/routes.rb
Rails.application.routes.draw do
  resources :organizations, except: :index, path: 'verbaende'
  get '/verbaende', to: redirect('/'), as: :organizations_index

  # resources :documents, path: 'd'
  resources :ministries, path: 'ministerien'

  resources :laws, path: 'gesetze' do
    resources :drafts, except: :index
    resources :comments, path: 's', except: :index
  end

  get 'status' => 'site#status'

  get '/:letter', to: 'site#index', constraints: { letter: /[[:alpha:]]{1,2}/ }

  root 'site#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <%= title site: 'stellungnah.me', separator: '-', reverse: 'true' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width">
  <%= tag 'link', href: asset_path('favicon.png'), rel: 'icon', type: 'image/png' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= description %>
  <%= opengraph { |graph| graph.site_name 'stellungnah.me' } -%>
  <%= twitter_card('summary') { |card| card.site '@fragdenstaat' } -%>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!-- Entwickler*in? Auf der Suche nach Rohdaten oder einer API? Kommt bald. Ping auf twitter: @fragdenstaat -->
</head>
<body>
  <header class="main-header">
    <nav class="navbar navbar-static-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to 'stellungnah.me', root_url, class: 'navbar-brand' %>
        </div>

        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Verbände', organizations_path %></li>
          <li><%= link_to 'Gesetze', laws_path %></li>
          <li><%= link_to 'Ministerien', ministries_path %></li>
          <!--
          <li class="navbar-text">&amp;</li>
          <li><a href="#">Daten</a></li>
          -->
        </ul>
      </div>
    </nav>
  </header>

  <main>
    <%= yield %>
  </main>

  <footer class="main-footer">
    <div class="container">
      <h3>Ein Projekt von</h3>
      <div class="row">
        <div class="col-md-4">
          <a href="https://www.abgeordnetenwatch.de" class="footer-abg"><img src="<%= image_url 'abgeordnetenwatch-logo.svg' %>" alt="abgeordnetenwatch.de" role="presentation" /></a>
        </div>
        <div class="col-md-5">
          <a href="https://okfn.de" class="footer-okf"><img src="<%= image_url 'okfn-logo.svg' %>" alt="Open Knowledge Foundation Deutschland e.V." role="presentation" /></a>
        </div>
        <div class="col-md-2">
          <ul class="footer-nav">
            <li><a href="https://fragdenstaat.de/hilfe/ueber/impressum/">Kontakt &amp; Impressum</a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
  <%= render partial: 'site/tracking' -%>
</body>
</html>